name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for Opening This Issue, we will look into it soon!'
        pr-message: 'Thanks for Your Contribution. It will be reviewed soon, Useless Prs are Closed Immediately'
